spring:
  application:
    name: compte-service
  profiles:
    active: prod

server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  
      
      
 