#spring.application.name=details-client
#server.port=9999
#spring.profiles.active=test
#logging.level.com.netflix.discovery=off
#logging.level.fr.lmsys.client.services.AppelMicroService=info
    
##spring.zipkin.enabled=false
#spring.zipkin.base-url=http://localhost:9411
##https://github.com/kbastani/spring-cloud-microservice-example/tree/master/movies-ui A VOIR

#spring:
#  profiles:
#    active:test
server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true